### PR TITLE
Add legacy "e3sm_coupling" script from COMPASS

### PR DESCRIPTION
**Pull request by xylar**
This script produces MPAS-Ocean and MPAS-Seaice initial conditions from a standalone MPAS-Ocean spin-up run.  It also produces scrip files, masks for MPAS-Ocean analysis members, masks and mapping files for MPAS-Analysis, and partition files for MPAS-Ocean.

### CODE REVIEW

**Comment by xylar** [comment]
I made a `legacy` directory for this stuff and any other scripts that have hard-coded paths and such that require a lot of user modification to be useful.  My hope is that we will eventually move the functionality from `legacy` into a set of scripts or a conda package or something like that that will be more portable and easier for new users to understand.

**Comment by xylar** [comment]
@jonbob, I'm mainly asking for your review to make sure you're good with the README.

@mark-petersen, I'm mainly asking for your review to give you a heads-up that I plan to move this content here and gradually drop it from COMPASS

@vanroekel, I'm mostly keeping you in the loop but please feel free to give feedback.

**Comment by mark-petersen** [comment]
@xylar thanks for working on this. You put the binary .swp file in by mistake, right? Best to `--amend` the last commit, otherwise it just stays in the repo forever.

**Comment by xylar** [comment]
@mark-petersen, thanks very much for noticing the swap file.  It has been removed from the commit.

**Comment by vanroekel** [comment]
@xylar I like the structure you add here and think the README looks great.

**Review by vanroekel — APPROVED** [review]

**Review by mark-petersen — APPROVED** [review]
Thanks for working on this, @xylar

**Comment by xylar** [comment]
@jonbob, could you review this when you get a chance?  Or remove yourself as a reviewer if you prefer not to.

**Comment by jonbob** [comment]
Sorry @xylar -- this one slipped off my radar. I'll review it this morning

**Review by jonbob — APPROVED** [review]
Looks great from a visual inspection

**Comment by xylar** [comment]
Thanks everyone!

**Pull request merged**
